######################################################################
# Automatically generated by qmake (2.01a) sb set 24 11:08:02 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += aestrella.h \
           agente.h \
           algoritmos.h \
           amplitud.h \
           avara.h \
           costouniforme.h \
           imagencarro.h \
           mapa.h \
           nodo.h \
           profundidadevitandociclos.h \
           ventana.h
FORMS += ventana.ui
SOURCES += aestrella.cpp \
           agente.cpp \
           algoritmos.cpp \
           amplitud.cpp \
           avara.cpp \
           costouniforme.cpp \
           imagencarro.cpp \
           main.cpp \
           mapa.cpp \
           nodo.cpp \
           profundidadevitandociclos.cpp \
           ventana.cpp

OTHER_FILES += \
    Documentacion/ejemplo4.in \
    Documentacion/ejemplo.in \
    Documentacion/ejemplo2.in \
    Documentacion/ejemplo3.in \
    Documentacion/ejemplo5.in \
    Documentacion/ejemplo6.in








